using System.Collections.Generic;
using static PokemonRandomizer.Backend.DataStructures.MoveData;

namespace PokemonRandomizer.Backend.Utilities
{
    public static class MoveDataUtils
    {
        static MoveDataUtils()
        {
            moveEffectToGenIVInternal = new Dictionary<MoveEffect, int>(genIVInternalToMoveEffect.Length);
            for (int i = 0; i < genIVInternalToMoveEffect.Length; ++i)
            {
                if (moveEffectToGenIVInternal.ContainsKey(genIVInternalToMoveEffect[i]))
                    continue;
                moveEffectToGenIVInternal.Add(genIVInternalToMoveEffect[i], i);
            }
        }
        private static readonly MoveEffect[] genIVInternalToMoveEffect = new MoveEffect[]
        {
            MoveEffect.Damage,
            MoveEffect.StatusSleep,
            MoveEffect.DamagePoisonChance,
            MoveEffect.DamageStealHp,
            MoveEffect.DamageBurnChance,
            MoveEffect.DamageFreezeChance,
            MoveEffect.DamageParalyzeChance,
            MoveEffect.Selfdestruct,
            MoveEffect.DreamEater,
            MoveEffect.MirrorMove,
            MoveEffect.AtkPlus1,
            MoveEffect.DefPlus1,
            MoveEffect.SpdPlus1,
            MoveEffect.SpAtkPlus1,
            MoveEffect.SpDefPlus1,
            MoveEffect.AccPlus1,
            MoveEffect.EvadePlus1,
            MoveEffect.DamageAlwaysHit,
            MoveEffect.AtkMinus1,
            MoveEffect.DefMinus1,
            MoveEffect.SpdMinus1,
            MoveEffect.SpAtkMinus1,
            MoveEffect.SpDefMinus1,
            MoveEffect.AccMinus1,
            MoveEffect.EvadeMinus1,
            MoveEffect.Haze,
            MoveEffect.Bide,
            MoveEffect.AttackUntilConfused,
            MoveEffect.ForceSwitch,
            MoveEffect.Multihit,
            MoveEffect.Conversion,
            MoveEffect.DamageFlinchChance,
            MoveEffect.RecoverHp,
            MoveEffect.StatusBadlyPoison,
            MoveEffect.PayDay,
            MoveEffect.LightScreen,
            MoveEffect.TriAttack,
            MoveEffect.Rest,
            MoveEffect.OneHitKill,
            MoveEffect.ChargeTurnHighCrit,
            MoveEffect.HalfHp,
            MoveEffect.FlatDamage40,
            MoveEffect.DoTTrap,
            MoveEffect.DamageHighCrit,
            MoveEffect.DamageTwoHit,
            MoveEffect.DamageMissHurtsSelf,
            MoveEffect.Mist,
            MoveEffect.StatusCritRateUp,
            MoveEffect.DamageRecoilOneFourth,
            MoveEffect.StatusConfuse,
            MoveEffect.AtkPlus2,
            MoveEffect.DefPlus2,
            MoveEffect.SpdPlus2,
            MoveEffect.SpAtkPlus2,
            MoveEffect.SpDefPlus2,
            MoveEffect.AccPlus2,
            MoveEffect.EvadePlus2,
            MoveEffect.Transform,
            MoveEffect.AtkMinus2,
            MoveEffect.DefMinus2,
            MoveEffect.SpdMinus2,
            MoveEffect.SpAtkMinus2,
            MoveEffect.SpDefMinus2,
            MoveEffect.AccMinus2, // TODO: Test 
            MoveEffect.EvadeMinus2, // TODO: Test
            MoveEffect.Reflect,
            MoveEffect.StatusPoison,
            MoveEffect.StatusParalyze,
            MoveEffect.DamageAtkMinus1Chance,
            MoveEffect.DamageDefMinus1Chance,
            MoveEffect.DamageSpdMinus1Chance,
            MoveEffect.DamageSpAtkMinus1Chance,
            MoveEffect.DamageSpDefMinus1Chance,
            MoveEffect.DamageAccMinus1Chance,
            MoveEffect.DamageEvadeMinus1Chance,
            MoveEffect.SkyAttack,
            MoveEffect.DamageConfuseChance,
            MoveEffect.DamageTwoHitPoisonChance,
            MoveEffect.DamagePriorityNeg1AlwaysHit,
            MoveEffect.Substitute,
            MoveEffect.DamageTiredAfterUse,
            MoveEffect.Rage,
            MoveEffect.Mimic,
            MoveEffect.Metronome,
            MoveEffect.StatusLeechSeed,
            MoveEffect.DoNothing,
            MoveEffect.Disable,
            MoveEffect.FlatDamageLevel,
            MoveEffect.VaryingDamageLevel,
            MoveEffect.Counter,
            MoveEffect.Encore,
            MoveEffect.PainSplit,
            MoveEffect.DamageFailUnlessAsleepFlinchChance,
            MoveEffect.Conversion2,
            MoveEffect.NextMoveAlwaysHits,
            MoveEffect.Sketch,
            (MoveEffect)96, // Unknown
            MoveEffect.SleepTalk,
            MoveEffect.DestinyBond,
            MoveEffect.DamageMoreAtLowHP,
            MoveEffect.Spite,
            MoveEffect.DamageCannotKill,
            MoveEffect.CurePartyStatus,
            MoveEffect.DamageHighPriority,
            MoveEffect.DamageThreeConsecutiveHits,
            MoveEffect.DamageStealHeldItem,
            MoveEffect.Trap,
            MoveEffect.StatusNightmare,
            MoveEffect.EvadePlus2AndMinimize,
            MoveEffect.Curse,
            (MoveEffect)110, // Unknown
            MoveEffect.Protect,
            MoveEffect.Spikes,
            MoveEffect.Foresight,
            MoveEffect.PerishSong,
            MoveEffect.WeatherSandstorm,
            MoveEffect.Endure,
            MoveEffect.MultiTurnBuildup, // Rollout, Ice Ball
            MoveEffect.StatusConfuseAtkPlus2,
            MoveEffect.FuryCutter,
            MoveEffect.Attract,
            MoveEffect.DamagePowerUpIfFriendly,
            MoveEffect.Present,
            MoveEffect.DamagePowerDownIfFriendly,
            MoveEffect.Safeguard,
            MoveEffect.DamageBurnChanceThaw,
            MoveEffect.Magnitude,
            MoveEffect.BatonPass,
            MoveEffect.Pursuit,
            MoveEffect.DamageRemoveHazardsAndBinding, // Rapid Spin
            MoveEffect.FlatDamage20,
            (MoveEffect)131, // Unknown
            MoveEffect.RecoverHpWeather1,
            (MoveEffect)133, // Unknown
            (MoveEffect)134, // Unknown
            MoveEffect.HiddenPower,
            MoveEffect.WeatherRain,
            MoveEffect.WeatherSun,
            MoveEffect.DamageDefPlus1Chance,
            MoveEffect.DamageAtkPlus1Chance,
            MoveEffect.DamageAllStatsPlus1Chance,
            (MoveEffect)141, // Unknown
            MoveEffect.HalfHpMaxAttack,
            MoveEffect.PsychUp,
            MoveEffect.MirrorCoat,
            MoveEffect.SkullBash,
            MoveEffect.DamageHitSky2xFlinchChance,
            MoveEffect.DamageHitUnderground2x,
            MoveEffect.FutureAttack,
            MoveEffect.DamageHitSky2x,
            MoveEffect.DamageFlinchChanceHitMinimized2x,
            MoveEffect.Solarbeam,
            MoveEffect.Thunder,
            MoveEffect.Teleport,
            MoveEffect.MultiHitPartyMembers,
            MoveEffect.DamageSpendTurnInSky,
            MoveEffect.DefPlus1AndPrepForRoll,
            (MoveEffect)157, // Softboiled uses RecoverHp (32) in Gen IV
            MoveEffect.DamagePriorityFlinchChance1stTurnOnly, // Fake out
            MoveEffect.Uproar,
            MoveEffect.Stockpile,
            MoveEffect.SpitUp,
            MoveEffect.Swallow,
            (MoveEffect)163,
            MoveEffect.WeatherHail,
            MoveEffect.Torment,
            MoveEffect.StatusConfuseSpAtkPlus2,
            MoveEffect.StatusBurn,
            MoveEffect.Memento,
            MoveEffect.Facade,
            MoveEffect.FocusPunch,
            MoveEffect.SmellingSalt,
            MoveEffect.FollowMe,
            MoveEffect.NaturePower,
            MoveEffect.Charge,
            MoveEffect.Taunt,
            MoveEffect.HelpingHand,
            MoveEffect.SwapItems,
            MoveEffect.RolePlay,
            MoveEffect.Wish,
            MoveEffect.Assist,
            MoveEffect.Ingrain,
            MoveEffect.Superpower,
            MoveEffect.MagicCoat,
            MoveEffect.Recycle,
            MoveEffect.Revenge,
            MoveEffect.DamageBreakBarriers,
            MoveEffect.Yawn,
            MoveEffect.KnockOff,
            MoveEffect.Endeavor,
            MoveEffect.DamageLessAtLowHp,
            MoveEffect.SkillSwap,
            MoveEffect.Imprison,
            MoveEffect.CureStatus,
            MoveEffect.Grudge,
            MoveEffect.Snatch,
            MoveEffect.DamageWeightBased,
            MoveEffect.SecretPower,
            MoveEffect.RecoilOneThird,
            MoveEffect.StatusConfuseAll,
            MoveEffect.DamageHighCritBurnChance,
            MoveEffect.MudSport,
            MoveEffect.DamageBadlyPoisonChance,
            MoveEffect.WeatherBall,
            MoveEffect.DamageSpAtkMinus2,
            MoveEffect.AtkDefMinus1,
            MoveEffect.DefSpDefPlus1,
            MoveEffect.DamageHitSky,
            MoveEffect.AtkDefPlus1,
            MoveEffect.DamageHighCritPoisonChance,
            MoveEffect.WaterSport,
            MoveEffect.SpAtkSpDefPlus1,
            MoveEffect.DragonDance,
            MoveEffect.Camouflage,
            MoveEffect.Roost,
            MoveEffect.Gravity,
            MoveEffect.MiracleEye, // Remove dark immunity and ignore ACC
            MoveEffect.WakeupSlap,
            MoveEffect.DamageSpdMinus1, // Hammer arm
            MoveEffect.DamageMoreLowerSpeed,
            MoveEffect.HealingWish,
            MoveEffect.DamageDoubleIfTargetBelowHalfHp,
            MoveEffect.NaturalGift,
            MoveEffect.Feint,
            MoveEffect.DamageEatBerry,
            MoveEffect.Tailwind,
            MoveEffect.RandomStatPlus2,
            MoveEffect.MetalBurst,
            MoveEffect.DamageThenSwitchOut,
            MoveEffect.DamageDefSpDefMinus1, // Close Combat, etc.
            MoveEffect.DamageDoubleIfAfterTarget, // Payback
            MoveEffect.DamageDoubleIfTargetAlreadyHit, // Assurance
            MoveEffect.Embargo,
            MoveEffect.Fling,
            MoveEffect.TransferStatus,
            MoveEffect.DamageHigherWhenLowPP,
            MoveEffect.HealBlock,
            MoveEffect.DamageMoreIfTargetHighHp,
            MoveEffect.SwapAtkDef,
            MoveEffect.SupressAbility,
            MoveEffect.LuckyChant,
            MoveEffect.MeFirst,
            MoveEffect.CopyCat,
            MoveEffect.SwapAtkSpAtkChanges,
            MoveEffect.SwapDefSpDefChanges,
            MoveEffect.DamageTargetStatUpDependent,
            MoveEffect.DamageFailIfNotLastMove,
            MoveEffect.SetAbilityToInsomnia,
            MoveEffect.DamageHitFirstIfTargetAttacking, // Sucker punch
            MoveEffect.ToxicSpikes,
            MoveEffect.SwapStatChanges,
            MoveEffect.RestoreHpEveryTurn,
            MoveEffect.MagnetRise,
            MoveEffect.DamageRecoilOneThirdBurnChanceThaw,
            MoveEffect.Struggle,
            MoveEffect.DamageSpendTurnUnderwater,
            MoveEffect.DamageSpendTurnUnderground,
            MoveEffect.DamageHitUnderwater2x,
            MoveEffect.ClearFieldEvadeMinus1,
            MoveEffect.TrickRoom,
            MoveEffect.Blizzard,
            MoveEffect.DoTTrapHitUnderwater2x,
            MoveEffect.DamageRecoilOneThirdParalyzeChance,
            MoveEffect.DamageSpendTurnInSkyParalyzeChance,
            (MoveEffect)264, // Unknown
            MoveEffect.SpAtkMinus2OppositeGender,
            MoveEffect.StealthRock,
            MoveEffect.Chatter,
            MoveEffect.Judgement,
            MoveEffect.DamageRecoilOneHalf,
            MoveEffect.LunarDance,
            MoveEffect.DamageSpAtkMinus2Chance,
            MoveEffect.DamageSpendTurnInShadowRealm,
            MoveEffect.DamageFlinchBurnChance,
            MoveEffect.DamageFlinchFreezeChance,
            MoveEffect.DamageFlinchParalyzeChance,
            MoveEffect.DamageSpAtkPlus1Chance,
        };
        private static readonly Dictionary<MoveEffect, int> moveEffectToGenIVInternal;

        public static MoveEffect Gen4InternalToMoveEffect(int gen4InternalIndex)
        {
            return genIVInternalToMoveEffect[gen4InternalIndex];
        }

        public static int MoveEffectToGen4Internal(MoveEffect effect)
        {
            return moveEffectToGenIVInternal[effect];
        }
    }
}
